"""empty message

Revision ID: 7adb66392eed
Revises: 7afbd7cbc848
Create Date: 2020-11-22 23:39:54.648152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7adb66392eed'
down_revision = '7afbd7cbc848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
